//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quandl.Excel.UDF.Functions.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quandl.Excel.UDF.Functions.Locale.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add additional query parameters to your formula..
        /// </summary>
        internal static string AdditionalQueryParamsPleaseAdd {
            get {
                return ResourceManager.GetString("AdditionalQueryParamsPleaseAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have specified a QTABLE formula with no query parameters. This may take a long time to run and may result in more data than can fit in excel. Are you sure you wish to continue?.
        /// </summary>
        internal static string AdditionalQueryParamsRequiredDesc {
            get {
                return ResourceManager.GetString("AdditionalQueryParamsRequiredDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Long Running Formula.
        /// </summary>
        internal static string AdditionalQueryParamsRequiredTitle {
            get {
                return ResourceManager.GetString("AdditionalQueryParamsRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quandl formulas have been turned off. Please enable Quandl formulas and then click the &apos;Refresh&apos; button..
        /// </summary>
        internal static string AutoDownloadTurnedOff {
            get {
                return ResourceManager.GetString("AutoDownloadTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid collapse parameter given : {collapse}.
        /// </summary>
        internal static string DatasetParamsInvalidCollapse {
            get {
                return ResourceManager.GetString("DatasetParamsInvalidCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date filters specified. Please ensure a maximum of two dates are given and they are in the format YYYY-MM-DD..
        /// </summary>
        internal static string DatasetParamsInvalidDateFilters {
            get {
                return ResourceManager.GetString("DatasetParamsInvalidDateFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transformation parameter given : {transformation}.
        /// </summary>
        internal static string DatasetParamsInvalidTransformation {
            get {
                return ResourceManager.GetString("DatasetParamsInvalidTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit must be above zero for data to be returned..
        /// </summary>
        internal static string DatasetParamsLimitZeroOrBelow {
            get {
                return ResourceManager.GetString("DatasetParamsLimitZeroOrBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{key}&apos; cannot be used directly as a query parameter..
        /// </summary>
        internal static string DatatableParamInvalid {
            get {
                return ResourceManager.GetString("DatatableParamInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{key}&apos; has been specified with a null value..
        /// </summary>
        internal static string DatatableParamNullValue {
            get {
                return ResourceManager.GetString("DatatableParamNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{value}&apos; has been specified without a key..
        /// </summary>
        internal static string DatatableParamWithoutKey {
            get {
                return ResourceManager.GetString("DatatableParamWithoutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save your API key under Settings to access premium data..
        /// </summary>
        internal static string MessageBoxText {
            get {
                return ResourceManager.GetString("MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API Key Set!.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formula did not fully complete..
        /// </summary>
        internal static string UdfCompleteError {
            get {
                return ResourceManager.GetString("UdfCompleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data retrieved successfully.
        /// </summary>
        internal static string UdfCompleteSuccess {
            get {
                return ResourceManager.GetString("UdfCompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your api key to begin pulling data..
        /// </summary>
        internal static string UdfRequiresAPIKey {
            get {
                return ResourceManager.GetString("UdfRequiresAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data ....
        /// </summary>
        internal static string UdfRetrievingData {
            get {
                return ResourceManager.GetString("UdfRetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved {currentRow} rows. Continuing ....
        /// </summary>
        internal static string UdfRetrievingDataMoreDetails {
            get {
                return ResourceManager.GetString("UdfRetrievingDataMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping data fetch as per user request. Data would have been overwritten..
        /// </summary>
        internal static string WarningOverwriteNotAccepted {
            get {
                return ResourceManager.GetString("WarningOverwriteNotAccepted", resourceCulture);
            }
        }
    }
}
