//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quandl.Excel.Addin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quandl.Excel.Addin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available for download.
        /// </summary>
        internal static string CheckUpdateNewUpdateAvailable {
            get {
                return ResourceManager.GetString("CheckUpdateNewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available for download.
        /// </summary>
        internal static string CheckUpdateNoUpdateAvailable {
            get {
                return ResourceManager.GetString("CheckUpdateNoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Note for {0}.
        /// </summary>
        internal static string CheckUpdatesReleaseNoteTitle {
            get {
                return ResourceManager.GetString("CheckUpdatesReleaseNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid code..
        /// </summary>
        internal static string DataCodeValidationMessage {
            get {
                return ResourceManager.GetString("DataCodeValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the {0} you want to see the data for..
        /// </summary>
        internal static string DatatableFilterDateRange {
            get {
                return ResourceManager.GetString("DatatableFilterDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in the {0} that you would like the data for..
        /// </summary>
        internal static string DatatableFilterFloatNumber {
            get {
                return ResourceManager.GetString("DatatableFilterFloatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in the {0} that you would like the data for..
        /// </summary>
        internal static string DatatableFilterIntegerNumber {
            get {
                return ResourceManager.GetString("DatatableFilterIntegerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify how you would like to filter data with any of the options below or none..
        /// </summary>
        internal static string DatatableFilterNoteOne {
            get {
                return ResourceManager.GetString("DatatableFilterNoteOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you skip this step, then you will receive all of the data for the for the columns you have selected previously..
        /// </summary>
        internal static string DatatableFilterNoteTwo {
            get {
                return ResourceManager.GetString("DatatableFilterNoteTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in the {0} that you would like to filter on. Separate each item with a comma..
        /// </summary>
        internal static string DatatableFilterTicker {
            get {
                return ResourceManager.GetString("DatatableFilterTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disable {
            get {
                object obj = ResourceManager.GetObject("disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enable {
            get {
                object obj = ResourceManager.GetObject("enable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileSave {
            get {
                object obj = ResourceManager.GetObject("FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap formulas_disabled {
            get {
                object obj = ResourceManager.GetObject("formulas_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap formulas_enabled {
            get {
                object obj = ResourceManager.GetObject("formulas_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap get_data {
            get {
                object obj = ResourceManager.GetObject("get_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered invalid API key..
        /// </summary>
        internal static string InvalidApiKeyEntered {
            get {
                return ResourceManager.GetString("InvalidApiKeyEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invalid domain..
        /// </summary>
        internal static string InvalidDomainEntered {
            get {
                return ResourceManager.GetString("InvalidDomainEntered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon quandl {
            get {
                object obj = ResourceManager.GetObject("quandl", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quandl_hq {
            get {
                object obj = ResourceManager.GetObject("quandl_hq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quandl_hq_sqr {
            get {
                object obj = ResourceManager.GetObject("quandl_hq_sqr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quandl_lq_sqr {
            get {
                object obj = ResourceManager.GetObject("quandl_lq_sqr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_sheet {
            get {
                object obj = ResourceManager.GetObject("refresh_sheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_workbook {
            get {
                object obj = ResourceManager.GetObject("refresh_workbook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login credentials..
        /// </summary>
        internal static string SettingsIncorrectCredentials {
            get {
                return ResourceManager.GetString("SettingsIncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password is incorrect..
        /// </summary>
        internal static string SettingsIncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("SettingsIncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your API key..
        /// </summary>
        internal static string SettingsInValidApiKey {
            get {
                return ResourceManager.GetString("SettingsInValidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Confirmation.
        /// </summary>
        internal static string SettingsSaveConfirmation {
            get {
                return ResourceManager.GetString("SettingsSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save?.
        /// </summary>
        internal static string SettingsSaveWarning {
            get {
                return ResourceManager.GetString("SettingsSaveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later. .
        /// </summary>
        internal static string SettingsSomethingWrongTryLater {
            get {
                return ResourceManager.GetString("SettingsSomethingWrongTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_available {
            get {
                object obj = ResourceManager.GetObject("update_available", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_check {
            get {
                object obj = ResourceManager.GetObject("update_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Data.
        /// </summary>
        internal static string UpdateCaption {
            get {
                return ResourceManager.GetString("UpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your workbook(s) contain Quandl formulas. Would you like to update your data?.
        /// </summary>
        internal static string UpdateWorkbookFormulas {
            get {
                return ResourceManager.GetString("UpdateWorkbookFormulas", resourceCulture);
            }
        }
    }
}
